language: php

before_script:
  - phpenv config-add travis.ini
  - composer install

php:
  - 5.5
  - 5.6
  - hhvm

services:
  - redis-server
  - memcached

matrix:
  allow_failures:
    - php: hhvm

script: vendor/bin/phpunit