language: php

before_script:
  - composer install

php:
  - 5.5
  - 5.6
  - hhvm

services:
  - redis-server
  - memcached

matrix:
  allow_failures:
    - php: hhvm

before_script: phpenv config-add travis.ini

script: phpunit